name: Build and Upload

on:
  - push
  - workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build SRPM and Upload Copr
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c '
          dnf install -y rpmdevtools copr-cli &&
          for spec in SPECS/*.spec; do
            spectool --directory SOURCES --get-files --all $spec &&
            rpmbuild --define "_topdir /workspace" -bs $spec &&
            rm -f SOURCES/LICENSE
          done &&
          echo "${{ secrets.COPR_API }}" > copr-api &&
          . /etc/os-release &&
          copr-cli --config copr-api build --nowait --chroot ${ID}-${VERSION_ID}-$(uname -m) $(echo ${{ github.repository }} | cut -d "-" -f 2-) SRPMS/*.src.rpm
        '
