name: Build and Upload

on:
  - push
  - workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build SRPM and Upload Copr
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c '
          dnf install -y dnf-plugins-core rpm-build copr-cli &&
          spectool --get-files --all SPECS/*.spec &&
          dnf builddep -y SPECS/*.spec &&
          rpmbuild --define "_topdir /workspace" -bs SPECS/*.spec &&
          echo "${{ secrets.COPR_API }}" > copr-api &&
          . /etc/os-release &&
          copr-cli --config copr-api build --nowait --chroot ${ID}-${VERSION_ID}-$(uname -m) ${{ github.repository##*/fedora- }} SRPMS/*.src.rpm
        '
