name: Build and Upload

on:
  - push

jobs:
  job:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: dnf install -y rpmdevtools copr-cli

    - name: Build SRPM
      run: |
        for spec in SPECS/*.spec; do
          spectool --directory SOURCES --get-files --all $spec &&
          rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -bs $spec
        done

    - name: Upload Copr
      run: |
        echo "${{ secrets.COPR_API }}" > copr-api &&
        . /etc/os-release &&
        copr-cli --config copr-api build --nowait --chroot ${ID}-${VERSION_ID}-$(uname -m) $(echo ${{ github.repository }} | cut -d "-" -f 2-) SRPMS/*.src.rpm &&
        rm -f copr-api
